/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StarRating.java
 *
 * Created on 25 Μαϊ 2010, 10:07:25 πμ
 */
package com.googlecode.starrating;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * StarRating Class
 * StarRating is a JPanel that holds 10 images of half stars (5 stars in total)
 * The rate ranges from 0.5 to 5.0
 * When a star is clicked a property change event is fired. The properties name is
 * {@link #RATE_CHANGED}.
 * @author ssoldatos
 */
public class StarRating extends javax.swing.JPanel {

  private double rate;
  private int maxRate = 5;
  private Star[] stars = new Star[maxRate*2];
  private ValueLabel valueLabel = new ValueLabel();
  private RemoveButton removeButton = new RemoveButton();
  private JPanel starPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 0));
  private JPanel valuePanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 0, 0));
  private boolean valueLabelShown = false;
  private boolean removeButtonShown = true;
  public static String RATE_CHANGED = "RATE_CHANGED";

  /**
   * Creates a default StarRating with a rate of 0
   */
  public StarRating() {
    this(0.0);
  }

  /** Creates a StarRating with the initial rate of rate
   * @param rate The initial rate
   */
  public StarRating(double rate) {
    initComponents();
    starPanel.setOpaque(false);
    valuePanel.setOpaque(false);
    starPanel.add(removeButton);

    for (int i = 0; i < stars.length; i++) {
      boolean enabled;
      enabled = i <= rate*2 ? true : false;
      stars[i] = new Star(i, enabled);
      starPanel.add(stars[i]);

    }
    setRate(rate);
    valueLabel.setValue(rate);
    
    add(starPanel, BorderLayout.CENTER);
    add(valuePanel, BorderLayout.EAST);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setBackground(new java.awt.Color(255, 255, 255));
    setMaximumSize(new java.awt.Dimension(120, 20));
    setMinimumSize(new java.awt.Dimension(100, 20));
    setName("StarRating"); // NOI18N
    setPreferredSize(new java.awt.Dimension(120, 20));
    addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        formMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        formMouseExited(evt);
      }
    });
    setLayout(new java.awt.BorderLayout());
  }// </editor-fold>//GEN-END:initComponents

  private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
    if (isRatingEnabled()) {
      clearRate();
    }
  }//GEN-LAST:event_formMouseEntered

  private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
    if (isRatingEnabled()) {
      previewRate(getRate());
    }
  }//GEN-LAST:event_formMouseExited

  /**
   * Sets if StarRating is enabled
   * @param enabled
   */
  public void setRatingEnabled(boolean enabled) {
    setEnabled(enabled);
  }

  /**
   * Gets if StarRating is enabled
   * @return If StarRating is enabled
   */
  public boolean isRatingEnabled() {
    return isEnabled();
  }

  /**
   * Shows the value label should be shown next to the stars
   */
  public void showValueLabel() {
    valuePanel.add(getValueLabel());
    valueLabelShown = true;
  }

  /**
   * Hides the value label
   */
  public void hideValueLabel() {
    valuePanel.remove(getValueLabel());
    valueLabelShown = false;
  }

  void clearRate() {
    for (int i = 0; i < stars.length; i++) {
      Star star = stars[i];
      star.clearRate();
    }
  }

  void previewRate(double rate) {
    for (int i = 0; i < stars.length; i++) {
      Star star = stars[i];
      if (i < rate*2) {
        star.setRate();
      } else {
        star.clearRate();
      }
    }
    valueLabel.setValue(rate);
  }

  /**
   * Gets the rate
   * @return the rate
   */
  public double getRate() {
    return rate;
  }

  /**
   * Sets the rate
   * @param rate the rate to set
   */
  public void setRate(double rate) {
    double oldRate = this.rate;
    this.rate = rate;
    previewRate(rate);
    valueLabel.setValue(rate);
    firePropertyChange(RATE_CHANGED, oldRate, rate);
  }

  /**
   * Gets the value label
   * @return the valueLabel
   */
  public JLabel getValueLabel() {
    return valueLabel;
  }

  /**
   * Gets if value label is shown
   * @return the isValueLabelShown
   */
  public boolean isValueLabelShown() {
    return valueLabelShown;
  }
  /**
   * Gets the remove button
   * @return The remove button
   */
  public RemoveButton getRemoveButton(){
    return removeButton;
  }

  /**
   * Set if remove button is shown
   * @param remove If remove button is shown
   */
  public void setRemoveButtonShown(boolean remove){
    removeButtonShown = remove;
    if(remove){
      showRemoveButton();
    } else {
      hideRemoveButton();
    }
  }

  /**
   * Gets if remove button is shown
   * @return If remove button is shown
   */
  public boolean isRemoveButtonShown(){
    return removeButtonShown;
  }

   /**
   * Sets if the value label is shown
   * @param shown If the value label is shown
   */
  public void setValueLabelShown(boolean shown) {
    if (shown) {
      showValueLabel();
    } else {
      hideValueLabel();
    }
    valueLabelShown = shown;
  }

  private void hideRemoveButton() {
    starPanel.remove(removeButton);
    removeButtonShown = false;
  }

  private void showRemoveButton() {
    if(!isRemoveButtonShown()){
      starPanel.add(removeButton);
      removeButtonShown = true;
    }
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
