/*
 * @(#)StarRating.java	28/05/2010
 *
 * Copyright 2010 Spyros Soldatos
 */
package com.googlecode.starrating;

import java.awt.Dimension;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.event.CellEditorListener;

/**
 * StarRating Class
 * StarRating is a JPanel that holds images of half stars
 * The rate ranges from 0 to the number of stars with a step of 0.5.<br />
 * The rate is shown in the {@link ValueLabel} which can be visible or not<br />
 * A {@link RemoveButton} (which can be disabled too) sets the rate to 0.0 <br />
 * When the rate changes a property change event is fired.The properties name
 * is {@link #RATE_CHANGED}.
 * A {@link PropertyChangeListener} can be attached to the {@link StarRating} to
 * perform additional tasks (eg save rate to a database etc)<br />
 * When {@link StarRating} is used as a cell editor a {@link CellEditorListener}
 * can be attached to the editor  and listen for {@link CellEditorListener#editingStopped}
 * to get the {@link StarRating} new value.
 * @author ssoldatos
 * @since version 0.9
 */
public class StarRating extends javax.swing.JPanel {

  /** The rate */
  private double rate;
  /** The maximum rate*/
  private int maxRate;
  /** An ArrayList holding the StarRating stars */
  private ArrayList<Star> stars;
  /** The value label */
  private ValueLabel valueLabel;
  /** The remove button */
  private RemoveButton removeButton;
  /** If {@link #valueLabel} is shown */
  private boolean valueLabelShown = false;
  /** If {@link #removeButton} is shown */
  private boolean removeButtonShown = false;
  /** The property that changes when new rate is set */
  public static String RATE_CHANGED = "RATE_CHANGED";

  /**
   * Creates a default StarRating with a {@link #rate} of 0.0 and a
   * {@link #maxrate} of 5
   */
  public StarRating() {
    this(0.0, 5);
  }

  /**
   * Creates a StarRating with a initial rate
   * @param rate The rate
   */
  public StarRating(double rate) {
    this(rate, 5);
  }

  /**
   * Creates a StarRating with a maximun rate
   * @param maxRate The maximum rate
   */
  public StarRating(int maxRate) {
    this(0.0, maxRate);
  }

  /** Creates a StarRating with the initial rate and a maximum rate<br />
   * The {@link #removeButton} is shown by default while the {@link #valuelabel}
   * is hidden.
   * @param rate The initial rate
   * @param maxRate The maximum rate
   */
  public StarRating(double rate, int maxRate) {
    super();
    this.maxRate = maxRate;
    initComponents();
    stars = new ArrayList<Star>();
    valueLabel = new ValueLabel(rate);
    removeButton = new RemoveButton();
    setOpaque(false);
    for (int i = 0; i < getMaxRate() * 2; i++) {
      boolean enabled;
      enabled = i <= rate * 2 ? true : false;
      stars.add(i, new Star(i, enabled));
      add(stars.get(i));
      stars.get(i).addStarMouseAdapter();
    }
    setRate(rate);
    showRemoveButton();
    setPreferredSize(new Dimension(maxRate * 20 + 40, 20));
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setBackground(new java.awt.Color(255, 51, 51));
    setMaximumSize(new java.awt.Dimension(10000, 20));
    setMinimumSize(new java.awt.Dimension(150, 20));
    setName("StarRating"); // NOI18N
    setOpaque(false);
    setPreferredSize(new java.awt.Dimension(300, 20));
    addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        formMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        formMouseExited(evt);
      }
    });
    setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
  }// </editor-fold>//GEN-END:initComponents

  /**
   * If {@link StarRating} is enabled the rate is set to 0.0
   * @param evt The MouseEvent
   */
  private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
    if (isRatingEnabled()) {
      clearRate();
    }
  }//GEN-LAST:event_formMouseEntered

  /**
   * If {@link StarRating} is enabled the rate is unchanged
   * @param evt The MouseEvent
   */
  private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
    if (isRatingEnabled()) {
      previewRate(getRate());
    }
  }//GEN-LAST:event_formMouseExited

  /**
   * Sets if StarRating is enabled
   * @param enabled If rating is enabled
   */
  public void setRatingEnabled(boolean enabled) {
    setEnabled(enabled);
  }

  /**
   * Gets if StarRating is enabled
   * @return If StarRating is enabled
   */
  public boolean isRatingEnabled() {
    return isEnabled();
  }

  /**
   * Shows the value label next to the stars validates and repaints the StarRating
   */
  private void showValueLabel() {
    if (!isValueLabelShown()) {
      add(getValueLabel(), getComponentCount());
      valueLabelShown = true;
      validate();
      repaint();
    }
  }

  /**
   * Hides the value label validates and repaints the StarRating
   */
  private void hideValueLabel() {
    if (isValueLabelShown()) {
      remove(getValueLabel());
      valueLabelShown = false;
      validate();
      repaint();
    }
  }

  /**
   * Clears the rate (disables stars images) without setting the rate
   */
  void clearRate() {
    for (int i = 0; i < stars.size(); i++) {
      Star star = stars.get(i);
      star.disableStar();
    }
  }

  /**
   * Previews a new rate without setting it
   * @param rate The new rate
   */
  void previewRate(double rate) {
    for (int i = 0; i < stars.size(); i++) {
      Star star = stars.get(i);
      if (i < rate * 2) {
        star.enableStar();
      } else {
        star.disableStar();
      }
    }
    valueLabel.setValue(rate);
  }

  /**
   * Gets the rate
   * @return the rate
   */
  public double getRate() {
    return rate;
  }

  /**
   * Sets the rate and fires a property change to notify listeners
   * @param rate the rate to set
   */
  public void setRate(double rate) {
    double oldRate = this.rate;
    this.rate = rate;
    previewRate(rate);
    valueLabel.setValue(rate);
    firePropertyChange(RATE_CHANGED, oldRate, rate);
  }

  /**
   * Gets the value label
   * @return the valueLabel
   */
  public JLabel getValueLabel() {
    return valueLabel;
  }

  /**
   * Gets if value label is shown
   * @return the isValueLabelShown
   */
  public boolean isValueLabelShown() {
    return valueLabelShown;
  }

  /**
   * Gets the remove button
   * @return The remove button
   */
  public RemoveButton getRemoveButton() {
    return removeButton;
  }

  /**
   * Set if remove button is shown
   * @param remove If remove button is shown
   */
  public void setRemoveButtonShown(boolean remove) {
    if (remove) {
      showRemoveButton();
    } else {
      hideRemoveButton();
    }
    removeButtonShown = remove;
  }

  /**
   * Gets if remove button is shown
   * @return If remove button is shown
   */
  public boolean isRemoveButtonShown() {
    return removeButtonShown;
  }

  /**
   * Sets if the value label is shown
   * @param shown If the value label is shown
   */
  public void setValueLabelShown(boolean shown) {
    if (shown) {
      showValueLabel();
    } else {
      hideValueLabel();
    }
    valueLabelShown = shown;
  }

  /**
   * Hide the removeButton validates and repaints the StarRating
   */
  private void hideRemoveButton() {
    remove(removeButton);
    removeButtonShown = false;
    validate();
    repaint();
  }

  /**
   * Shows the removeButton validates and repaints the StarRating
   */
  private void showRemoveButton() {
    if (!isRemoveButtonShown()) {
      removeButton.setOpaque(false);
      add(removeButton, 0);
      removeButtonShown = true;
      validate();
      repaint();
    }
  }

  /**
   * @return the maxRate
   */
  public int getMaxRate() {
    return maxRate;
  }

  /**
   * Changes the maximum rate
   * @param maxRate the maxRate to set
   */
  public void setMaxRate(int maxRate) {
    if (maxRate > getMaxRate()) {
      for (int i = stars.size(); i < maxRate * 2; i++) {
        stars.add(i, new Star(i, false));
        add(stars.get(i), i + 1);
        stars.get(i).addStarMouseAdapter();
      }
    } else {
      for (int i = stars.size(); i > maxRate * 2; i--) {
        remove(stars.get(i-1));
        stars.remove(i-1);
      }
      if(getRate() > maxRate){
        setRate(maxRate);
      }
    }
    setPreferredSize(new Dimension(maxRate * 20 + 40, getHeight()));
    validate();
    repaint();
    this.maxRate = maxRate;
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
