/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * test.java
 *
 * Created on 25 Μαϊ 2010, 10:08:46 πμ
 */
package sstarrating;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ssoldatos
 */
public class test extends javax.swing.JFrame {

  /** Creates new form test */
  public test() {
    initComponents();
    setLocationRelativeTo(null);
    DefaultTableModel model =new DefaultTableModel(new String[]{"Title","Rating"}, 0);
    table.setModel(model);
    model.addRow(new Object[]{"PHP",5});
    model.addRow(new Object[]{"Java",6});
    model.addRow(new Object[]{"VBScript",3});
    model.addRow(new Object[]{"C++",7});
    table.getColumnModel().getColumn(1).setCellRenderer(new StarRenderer());
    table.getColumnModel().getColumn(1).setCellEditor(new StarEditor());

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    table = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new java.awt.FlowLayout());

    jScrollPane1.setViewportView(table);

    getContentPane().add(jScrollPane1);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new test().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable table;
  // End of variables declaration//GEN-END:variables
}
